### PR TITLE
Migrate bundler based project

### PR DESCRIPTION
**Pull request by cosmo0920**
Also I want to tidy up gem dependency with bundler.
But for now, I got the following tests failed:

* Windows 7 32bit CP932 (Japanese)
* Ruby 2.2.4

```log
> bundle exec rake test:all
# Running:

.........................F....F.................................................
................................................................................
............

Finished in 0.456015s, 377.1808 runs/s, 1767.4867 assertions/s.

  1) Failure:
TC_Windows_Unicode#test_multi_to_wide [C:/Users/hhatake/Documents/GitHub/windows
-pr/test/tc_unicode.rb:49]:
--- expected
+++ actual
@@ -1,2 +1,2 @@
 # encoding: ASCII-8BIT
-"\xCE\x00\" \xCE\x00\xBB\x00\xCE\x00\xBB\x00\xCE\x00\xAC\x00\xCF\x00\x92\x01\x0
0\x00"
+"\x8E\xFFOP{\xFF\x8E\xFF{\xFF\x8E\xFFl\xFF\x8F\xFF\xFB0\x00\x00"



  2) Failure:
TC_Windows_Unicode#test_wide_to_multi [C:/Users/hhatake/Documents/GitHub/windows
-pr/test/tc_unicode.rb:69]:
--- expected
+++ actual
@@ -1,2 +1,2 @@
 # encoding: ASCII-8BIT
-"\xCE\x95\xCE\xBB\xCE\xBB\xCE\xAC\xCF\x83"
+"I?I\x81\xE2I\x81\xE2I\x81\xCAI?"


172 runs, 806 assertions, 2 failures, 0 errors, 0 skips
rake aborted!
```

### CODE REVIEW

**Comment by cosmo0920** [comment]
Wow, GitHub's git repository branches are very wise!
`migrate-bundler-based-project` had been created old my forked repository, but I found that this PR can reopen! :open_mouth:

**Comment by cosmo0920** [comment]
Can I merge this?

I want to merge this change because this change makes to be more easily to construct development environment.

**Comment by phasis68** [comment]
Yes, you can merge.
It's your repository. You can do anything you want without asking.

**Comment by cosmo0920** [comment]
OK.
I'll merge this PR.
Even if this repository is mine, I'll use pull request to apply changes for the time being.

**Comment by cosmo0920** [comment]
> Even if this repository is mine, I'll use pull request to apply changes for the time being.

Main reason is waiting for CI results. (But, currently, there is no CI settings in this repository :cry: )

**Pull request merged**
